name: Repo Activity

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

# Keeps only one in-flight run per branch for this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  log:
    name: Log repo activity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Print event context
        run: |
          echo "event_name=$GITHUB_EVENT_NAME"
          echo "ref=$GITHUB_REF"
          echo "ref_name=$GITHUB_REF_NAME"
          echo "sha=$GITHUB_SHA"
          echo "actor=$GITHUB_ACTOR"
          echo "repo=$GITHUB_REPOSITORY"
          echo "run_id=$GITHUB_RUN_ID"
          echo "run_number=$GITHUB_RUN_NUMBER"

      - name: List changed files (push only)
        if: ${{ github.event_name == 'push' }}
        run: |
          git diff --name-status HEAD~1..HEAD | tee changed_files.txt

      - name: Save context as JSON
        run: |
          jq -n --arg event "$GITHUB_EVENT_NAME" \
                --arg ref "$GITHUB_REF" \
                --arg ref_name "$GITHUB_REF_NAME" \
                --arg sha "$GITHUB_SHA" \
                --arg actor "$GITHUB_ACTOR" \
                --arg repo "$GITHUB_REPOSITORY" \
                --arg run_id "$GITHUB_RUN_ID" \
                --arg run_number "$GITHUB_RUN_NUMBER" \
                '{event:$event, ref:$ref, ref_name:$ref_name, sha:$sha, actor:$actor, repo:$repo, run_id:$run_id, run_number:$run_number}' \
            | tee context.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repo-activity-${{ github.run_number }}
          path: |
            context.json
            changed_files.txt
          if-no-files-found: ignore

      - name: Add run summary
        run: |
          {
            echo "### Repo Activity"
            echo "- Event: **$GITHUB_EVENT_NAME**"
            echo "- Ref: **$GITHUB_REF_NAME**"
            echo "- SHA: \`$GITHUB_SHA\`"
            echo "- Actor: @$GITHUB_ACTOR"
            echo "- Run: $GITHUB_RUN_NUMBER"
            echo ""
            echo "**Last commit message (if available):**"
            echo ""
            echo '```'
            git log -1 --pretty=%B || echo "No commit message available"
            echo '```'
            echo ""
            echo "**Changed files (push events):**"
            if [ -f changed_files.txt ]; then
              echo ""
              echo '```'
              cat changed_files.txt
              echo '```'
            else
              echo "_No changed files list for this event_"
            fi
          } >> "$GITHUB_STEP_SUMMARY"
